[package]
name = "ml_analysis"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = { version = "0.26.0", features = ["auto-initialize"] }
serde_json = "1.0"
serde = { version = "1.0.228", features = ["derive"]}
numpy = "0.26.0"
