//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

pub mod prelude;

pub mod face_boxes;
pub mod gps;
pub mod locations;
pub mod metadata;
pub mod ocr_boxes;
pub mod tags;
pub mod times;
pub mod unique_faces;
pub mod users;
pub mod weather;
