//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

pub use super::face_boxes::Entity as FaceBoxes;
pub use super::gps::Entity as Gps;
pub use super::images::Entity as Images;
pub use super::locations::Entity as Locations;
pub use super::metadata::Entity as Metadata;
pub use super::object_boxes::Entity as ObjectBoxes;
pub use super::ocr_boxes::Entity as OcrBoxes;
pub use super::tags::Entity as Tags;
pub use super::unique_faces::Entity as UniqueFaces;
pub use super::users::Entity as Users;
pub use super::visual_features::Entity as VisualFeatures;
pub use super::weather::Entity as Weather;
