//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "visual_features")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub frame_percentage: i32,
    #[sea_orm(column_type = "custom(\"vector\")", select_as = "float4[]")]
    pub embedding: Vec<f32>,
    pub scene_type: String,
    pub people_type: Option<String>,
    pub animal_type: Option<String>,
    pub document_type: Option<String>,
    pub object_type: Option<String>,
    pub activity_type: Option<String>,
    pub event_type: Option<String>,
    pub weather_condition: Option<String>,
    pub is_outside: bool,
    pub is_landscape: bool,
    pub is_cityscape: bool,
    pub is_travel: bool,
    pub has_legible_text: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub ocr_text: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub document_summary: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub measured_sharpness: Option<f32>,
    pub measured_noise: Option<i32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub measured_brightness: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub measured_contrast: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub measured_clipping: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub measured_dynamic_range: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub quality_score: Option<f32>,
    pub summary: Option<String>,
    pub caption: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
