[package]
name = "photos_watcher"
version = "0.1.0"
edition = "2024"

[dependencies]
photos_core = { path = "../photos_core" }
sqlx = { version = "0.8.6", features = ["runtime-tokio-native-tls", "postgres", "chrono", "json"] }
futures = "0.3.31"
tokio = { version = "1.47.1", features = ["full"] }
color-eyre = "0.6.5"
notify = "8.2.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"