[package]
name = "worker"
version = "0.1.0"
edition = "2024"

[dependencies]
common_photos = { path = "../../libs/common_photos" }
generate_thumbnails = { path = "../../libs/generate_thumbnails" }
ml_analysis = { path = "../../libs/ml_analysis" }
media_analyzer = "0.3.4"
sqlx = { version = "0.8.6", features = ["runtime-tokio-native-tls", "postgres", "chrono", "macros", "json"] }
tokio = { version = "1.47.1", features = ["full"] }
color-eyre = "0.6.5"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
chrono = "0.4.42"
serde_json = "1.0.145"
pgvector = { version = "0.4", features = ["sqlx"] }
clap = { version = "4.5.48", features = ["derive"] }
walkdir = "2.5.0"
rand = "0.10.0-rc.0"
