directories:
  media_folder: media_dir
  thumbnails_folder: thumbnails

logging:
  level: "info"

api:
  host: "0.0.0.0"
  port: 8080
  allowed_origins:
    - "http://localhost:3000"

database:
  url: postgres://user:pass@localhost/photos
  pool_size: 10
  media_item_id_length: 10

worker:
  wait_after_empty_queue_s: 10
  wait_after_error_s: 5
  max_retries: 5

thumbnail_generation:
  heights:
    - 8
    - 144
    - 240
    - 360
    - 480
    - 720
    - 1080
  thumbnail_extension: "avif"
  avif_options:
    quality: 80
    alpha_quality: 80
    speed: 4
  video_options:
    extension: "webm"
    thumb_time: 0.5
    percentages:
      - 0
      - 33
      - 66
      - 99
    height: 720
    transcode_outputs:
      - height: 480
        quality: 35
      - height: 144
        quality: 40
  video_extensions:
    - "mp4"
    - "webm"
    - "av1"
    - "3gp"
    - "mov"
    - "mkv"
    - "flv"
    - "m4v"
    - "m4p"
  photo_extensions:
    - "jpg"
    - "jpeg"
    - "png"
    - "gif"
    - "tiff"
    - "tga"
    - "avif"